---
title: 'Code'
author: "Clare Robson"
date: "2024-09-4"
output: html_document
---

```{r}
library(readr)
library(tidyverse)
library(stringr)
library(ggplot2)
library(forecast)
```

```{r}
#load data
olympics <- read.csv("~/Desktop/ds340w/results (1).csv")
tokyo_olympics <- read.csv("~/Desktop/ds340w/2020Olympics.csv")
```

```{r}
#remove unneeded variables
olympics <- olympics %>%
  select("Gender", "Event", "Year", "Medal", "Result") %>%
  filter(Medal != "S")

head(olympics)
```

```{r}
#combine datasets
olympics <- rbind(olympics, tokyo_olympics)
```

```{r}
#convert time values to seconds
convert_to_seconds <- function(time_str) {
  ifelse(grepl(":", time_str), {
    parts <- strsplit(time_str, ":")[[1]]
    minutes <- as.numeric(parts[1])
    seconds <- as.numeric(parts[2])
    total_seconds <- minutes * 60 + seconds
  }, {
    as.numeric(time_str)
  })
}

olympics$Result <- sapply(olympics$Result, convert_to_seconds)
```

```{r}
#sprint and mid-distance events
events <- unique(olympics$Event)

selected_events <- events[events %in% c(
  "100M Men", "100M Women", "200M Men", "200M Women", "400M Men", "400M Women",
  "800M Men", "800M Women", "1500M Men", "1500M Women")]
```

```{r}
#create data sets for each selected event
for (event in selected_events) {
  event_data <- subset(olympics, Event == event)
  assign(paste0(gsub(" ", "_", event), "_data"), event_data)
}
```

```{r}
#get list of dataset names
dataset_names <- ls(pattern = "_data$")

#remove the event_data dataset from the list
dataset_names <- subset(dataset_names, dataset_names != "event_data")

print(dataset_names)
```

```{r}
#create separate datasets for each event containing gold and bronze times
for (event_data_name in dataset_names) {
  #get the dataset
  event_data <- get(event_data_name)
  
  #subset the dataset into gold and bronze subsets
  gold_data <- subset(event_data, Medal == "G")
  bronze_data <- subset(event_data, Medal == "B")
  
  #create new dataset names for gold and bronze data
  gold_dataset_name <- paste0(gsub("_data", "_gold_data", event_data_name))
  bronze_dataset_name <- paste0(gsub("_data", "_bronze_data", event_data_name))
  
  #assign gold and bronze datasets to the new dataset names
  assign(gold_dataset_name, gold_data)
  assign(bronze_dataset_name, bronze_data)
}
```


```{r}
#plot gold vs. bronze times for an event
plot_gold_vs_bronze <- function(event_data, event_name) {
  ggplot() + 
    geom_line(data = event_data[event_data$Medal == "G", ], aes(x = Year, y = Result, color = "gold", group = 1)) + 
    geom_line(data = event_data[event_data$Medal == "B", ], aes(x = Year, y = Result, color = "brown", group = 1)) +
    geom_point(data = event_data[event_data$Medal == "G", ], aes(x = Year, y = Result), color = "gold") +
    geom_point(data = event_data[event_data$Medal == "B", ], aes(x = Year, y = Result), color = "brown") +
    labs(title = paste(event_name, "- Gold vs. Bronze Times"), x = "Year", y = "Time (seconds)") +
    scale_color_manual(values = c(gold = "gold", brown = "brown")) +
    theme_minimal()
}

#loop over selected events and generate plot for each event
for (event in selected_events) {
  event_data <- subset(olympics, Event == event)
  plot <- plot_gold_vs_bronze(event_data, event)
  print(plot)
}

```

```{r}
#get the names of all objects in the environment
all_dataset_names <- ls()

#filter the names based on whether they end with "gold_data" or "bronze_data"
gold_dataset_names <- all_dataset_names[grep("gold_data$", all_dataset_names)]
bronze_dataset_names <- all_dataset_names[grep("bronze_data$", all_dataset_names)]

#exclude specific dataset names like "gold_data" and "bronze_data"
gold_dataset_names <- gold_dataset_names[!gold_dataset_names %in% c("gold_data", "bronze_data")]
bronze_dataset_names <- bronze_dataset_names[!bronze_dataset_names %in% c("gold_data", "bronze_data")]

#print the names of gold and bronze datasets
print(gold_dataset_names)
print(bronze_dataset_names)
```

```{r}
#remove outliers manually after examining plots

`800M_Women_gold_data` <- `800M_Women_gold_data` %>%
  filter(Year >= 1950)

`800M_Men_bronze_data` <- `800M_Men_bronze_data` %>%
  filter(Year >= 1900)

`400M_Men_bronze_data` <- `400M_Men_bronze_data` %>%
  filter(Year >= 1900)

`200M_Men_bronze_data` <- `200M_Men_bronze_data` %>%
  filter(Year >= 1900)

`100M_Men_bronze_data` <- `100M_Men_bronze_data` %>%
  filter(Year >= 1910)

`100M_Men_gold_data` <- `100M_Men_gold_data` %>%
  filter(Year >= 1910)
```


```{r}
#set seed for reproducibility
set.seed(2225)

#split data into training and testing sets
split_data <- function(data) {
  #get the number of rows in the data
  n_rows <- nrow(data)
  
  #sample indices for training data
  train_ind <- sample(1:n_rows, floor(0.80 * n_rows))
  
  #create training and testing sets
  train_data <- data[train_ind, ]
  test_data <- data[-train_ind, ]
  
  #return training and testing sets
  return(list(Train = train_data, Test = test_data))
}

#loop over each dataset containing gold times
for (dataset_name in gold_dataset_names) {
  dataset <- get(dataset_name)
  
  #split the dataset into training and testing sets
  split_data_list <- split_data(dataset)
  
  #assign the training and testing sets to new variables
  assign(paste0(dataset_name, "_Train"), split_data_list$Train)
  assign(paste0(dataset_name, "_Test"), split_data_list$Test)
}

#loop over each dataset containing bronze times
for (dataset_name in bronze_dataset_names) {
  dataset <- get(dataset_name)
  
  #split the dataset into training and testing sets
  split_data_list <- split_data(dataset)
  
  #assign the training and testing sets to new variables
  assign(paste0(dataset_name, "_Train"), split_data_list$Train)
  assign(paste0(dataset_name, "_Test"), split_data_list$Test)
}
```

```{r}
# working with the olympic dataset rather than the smaller ones
olympics_reduced <- olympics %>%
  filter(Event %in% selected_events) %>%
  mutate(male = ifelse(Gender == "M", 1, 0))
```

```{r}
# set seed for reproducibility
set.seed(2225)

#sample indices for training data
train_ind <- sample(1:nrow(olympics_reduced), floor(0.80 * nrow(olympics_reduced)))

#create training and testing sets
Train_olympics <- olympics_reduced[train_ind, ]
Test_olympics <- olympics_reduced[-train_ind, ]
``` 

```{r}
#visually examine a few dataset distributions -> they are right skewed and not consistently bell shaped
hist(`100M_Men_gold_data`$Result, breaks = 15)
hist(`200M_Men_gold_data`$Result, breaks = 20)
hist(`100M_Women_gold_data`$Result, breaks = 10)
hist(`400M_Men_gold_data`$Result, breaks = 15)
hist(`800M_Women_gold_data`$Result, breaks = 15)
hist(`1500M_Men_gold_data`$Result, breaks = 15)
```

```{r}
#test lm
lm_olympics <- lm(Result ~ Year, data = `100M_Men_gold_data_Train`)
summary(lm_olympics)
```

```{r}
#RMSE
predictions <- predict(lm_olympics, newdata = `100M_Men_gold_data_Test`)
MSE <- mean((`100M_Men_gold_data_Test`$Result - predictions)^2)
RMSE <- sqrt(MSE)
RMSE
MAE <- mean(abs(`100M_Men_gold_data_Test`$Result - predictions))
MAE
```


```{r}
#test lm with full dataset
olympics_lm <- lm(Result ~ Year + male + Medal + Event, data = Train_olympics)
summary(olympics_lm)
```

```{r}
predictions_ful <- predict(olympics_lm, newdata = Test_olympics)
MSE <- mean((Test_olympics$Result - predictions_ful)^2)
mean(abs(Test_olympics$Result - predictions_ful), na.rm = TRUE)
```

```{r}
#get all object names in the environment
all_objects <- ls()

#filter for training datasets
train_dataset_names <- grep("_Train$", all_objects, value = TRUE)

#filter for testing datasets
test_dataset_names <- grep("_Test$", all_objects, value = TRUE)
```

```{r}
# Create an empty data frame to store results
result_df <- data.frame(Race = character(),
                         LM_RMSE = numeric(),
                         LM_MAE = numeric(),
                         LM_2024_Predictions = numeric(),
                        Normalized_LM_RMSE = numeric(),
                        Normalized_LM_MAE = numeric(),
                         Medal = character())

# Loop over each dataset
for (dataset_name in train_dataset_names) {
  # Get the training dataset
  training_dataset <- get(dataset_name)
  
  # Get the corresponding testing dataset
  testing_dataset_name <- gsub("_Train", "_Test", dataset_name)
  testing_dataset <- get(testing_dataset_name)
  
  # Determine the race name
  race_name <- gsub("_bronze_data|_gold_data|_Train", "", dataset_name)
  
  # Fit the linear regression model
  lm_model <- lm(Result ~ Year, data = training_dataset)
  
  # Make predictions on the testing dataset
  predictions <- predict(lm_model, newdata = testing_dataset)
  
  # Calculate RMSE and MAE, ignoring NA values
  mse <- mean((testing_dataset$Result[!is.na(testing_dataset$Result)] - predictions[!is.na(testing_dataset$Result)])^2)
  rmse <- sqrt(mse)
  mae <- mean(abs(testing_dataset$Result[!is.na(testing_dataset$Result)] - predictions[!is.na(testing_dataset$Result)]))
  
  # Calculate average time for the race
  average_time <- mean(testing_dataset$Result, na.rm = TRUE)  # Assuming the time is in a column named 'Time'
  
  # Calculate normalized RMSE
  normalized_ln_mae <- mae / average_time
  normalized_ln_rmse <- rmse / average_time
  
  # Store the results
  result_df[nrow(result_df) + 1, ] <- c(race_name, rmse, mae, NA, normalized_ln_mae, normalized_ln_rmse, ifelse(grepl("gold", dataset_name), "G", "B"))
  
  # Predict results for the year 2024
  new_data_2024 <- data.frame(Year = 2024)
  predictions_2024 <- predict(lm_model, newdata = new_data_2024)
  
  # Store the 2024 predictions
  result_df[nrow(result_df), "LM_2024_Predictions"] <- predictions_2024
}

# Save the results to a CSV file
write.csv(result_df, "lm_results.csv", row.names = FALSE)
```


```{r}
lm_results <- read.csv("~/Desktop/ds340w/lm_results.csv")
head(lm_results, n = Inf)
```

```{r}
#modify to match format of original race results
transformed_results <- lm_results %>%
  rename(Event = Race, Result = LM_2024_Predictions) %>%
  mutate(Event = gsub("_", " ", Event),
         Gender = ifelse(substr(Event, nchar(Event) - 4, nchar(Event)) == "Women", "W", "M"),
         Year = 2024) %>%
  select(Event, Result, Gender, Year, Medal)

head(transformed_results)
```

```{r}
olympics_with_lm_predictions <- rbind(olympics, transformed_results)
```

```{r}
#plot and include 2024 predictions
for (event in selected_events) {
  event_data <- subset(olympics_with_lm_predictions, Event == event)
  plot <- plot_gold_vs_bronze(event_data, event)
  print(plot)
}
```

```{r}
`400M_Men_bronze_data_Train` <- `400M_Men_bronze_data_Train`[complete.cases(`400M_Men_bronze_data_Train`), ]
`800M_Women_bronze_data_Train` <-  `800M_Women_bronze_data_Train`[complete.cases( `800M_Women_bronze_data_Train`), ]
`1500M_Men_bronze_data_Train` <- `1500M_Men_bronze_data_Train`[complete.cases(`1500M_Men_bronze_data_Train`), ]
`200M_Men_bronze_data_Train` <- `200M_Men_bronze_data_Train`[complete.cases(`200M_Men_bronze_data_Train`), ]
```


```{r}
# Load necessary library
library(FNN)  # For KNN modeling

# Create an empty data frame to store results
knn_result_df <- data.frame(Race = character(),
                             KNN_RMSE = numeric(),
                             KNN_MAE = numeric(),
                             KNN_2024_Predictions = numeric(),
                            Normalized_KNN_MAE = numeric(),
                             Normalized_KNN_RMSE = numeric(),  # Add column for normalized RMSE
                            Medal = character())

# Loop over each dataset
for (dataset_name in train_dataset_names) {
  # Get the training dataset
  training_dataset <- get(dataset_name)
  
  # Get the corresponding testing dataset
  testing_dataset_name <- gsub("_Train", "_Test", dataset_name)
  testing_dataset <- get(testing_dataset_name)
  
  # Fit the KNN model using only the numeric columns
  numeric_cols <- sapply(training_dataset, is.numeric)  # Identify numeric columns
  training_numeric <- training_dataset[, numeric_cols]
  testing_numeric <- testing_dataset[, numeric_cols]
  training_numeric <- training_numeric[complete.cases(training_numeric), ]
  testing_numeric <- testing_numeric[complete.cases(testing_numeric), ]
  
  # Determine the race name
  race_name <- gsub("_bronze_data|_gold_data|_Train", "", dataset_name)
  
  # Fit the KNN model
  knn_model <- knn.reg(train = training_numeric,   # Use only numeric columns for training
                       test = testing_numeric,     # Use only numeric columns for testing
                       y = training_dataset$Result,   # Target variable
                       k = 3)   # Number of neighbors  
  
  # Make predictions on the testing dataset
  predictions <- knn_model$pred
  
  # Calculate RMSE and MAE, ignoring NA values
  na_indices <- !is.na(testing_numeric$Result)  # Indices of non-NA values
  mse <- mean((testing_numeric$Result[na_indices] - predictions[na_indices])^2)
  rmse <- sqrt(mse)
  mae <- mean(abs(testing_numeric$Result[na_indices] - predictions[na_indices]))
  
  # Calculate average time for the race
  average_time <- mean(testing_dataset$Result, na.rm = TRUE)  # Assuming the time is in a column named 'Time'
  
  # Calculate normalized RMSE
  normalized_knn_mae <- mae / average_time
  normalized_knn_rmse <- rmse / average_time
  
  # Store the results
  knn_result_df[nrow(knn_result_df) + 1, ] <- c(race_name, rmse, mae, NA, normalized_knn_mae, normalized_knn_rmse, ifelse(grepl("gold", dataset_name), "G", "B"))
  
  # Predict results for the year 2024
  new_data_2024 <- testing_numeric[1, ]
  new_data_2024$Year <- 2024
  predictions_2024_knn <- knn.reg(train = training_numeric,   # Use only numeric columns for training
                                  test = new_data_2024,      # New data for prediction
                                  y = training_dataset$Result,  # Target variable
                                  k = 3)$pred                # Number of neighbors
  
  # Store the 2024 predictions
  knn_result_df[nrow(knn_result_df), "KNN_2024_Predictions"] <- predictions_2024_knn
}

# Save the results to a CSV file
write.csv(knn_result_df, "knn_results.csv", row.names = FALSE)

```

```{r}
knn_results <- read.csv("~/Desktop/ds340w/knn_results.csv")
head(knn_results, n = Inf)
```

```{r}
RMSE <- lm_results %>%
  left_join(knn_results, by = c("Race", "Medal")) %>%
  select("Race", "Medal", "Normalized_LM_RMSE", "Normalized_KNN_RMSE", "Normalized_LM_MAE", "Normalized_KNN_MAE") %>%
  mutate(Smallest_RMSE = ifelse(Normalized_LM_RMSE < Normalized_KNN_RMSE, "LM", "KNN")) %>%
  mutate(Smallest_MAE = ifelse(Normalized_LM_MAE < Normalized_KNN_MAE, "LM", "KNN"))

head(RMSE, n = Inf)
```

```{r}
#modify to match format of original race results
transformed_results_knn <- knn_results %>%
  rename(Event = Race, Result = KNN_2024_Predictions) %>%
  mutate(Event = gsub("_", " ", Event),
         Gender = ifelse(substr(Event, nchar(Event) - 4, nchar(Event)) == "Women", "W", "M"),
         Year = 2024) %>%
  select(Event, Result, Gender, Year, Medal)

head(transformed_results_knn)
```

```{r}
olympics_with_knn_predictions <- rbind(olympics, transformed_results_knn)
```

```{r}
#plot and include 2024 predictions
for (event in selected_events) {
  event_data <- subset(olympics_with_knn_predictions, Event == event)
  plot <- plot_gold_vs_bronze(event_data, event)
  print(plot)
}
```


```{r}
# Create an empty data frame to store results
result_df <- data.frame(Race = character(),
                         AR_RMSE = numeric(),
                         AR_MAE = numeric(),
                         AR_2024_Predictions = numeric(),
                        Normalized_AR_RMSE = numeric(),
                        Normalized_AR_MAE = numeric(), 
                         Medal = character())

# Loop over each dataset
for (dataset_name in train_dataset_names) {
  # Get the training dataset
  training_dataset <- get(dataset_name)
  
  # Get the corresponding testing dataset
  testing_dataset_name <- gsub("_Train", "_Test", dataset_name)
  testing_dataset <- get(testing_dataset_name)
  
  # Determine the race name
  race_name <- gsub("_bronze_data|_gold_data|_Train", "", dataset_name)
  
  # Fit the autoregressive model with reduced model order
  max_order <- 3  # Set maximum model order
  for (order in max_order:1) {
    tryCatch({
      ar_model <- ar(training_dataset$Result, method = "ols", aic = FALSE, order.max = order)
      break  # Exit loop if model fitting succeeds without error
    }, error = function(e) {
      cat("Error occurred while fitting AR model with order:", order, "\n")
    })
  }
  
  # Make predictions on the testing dataset
  predictions <- predict(ar_model, n.ahead = length(testing_dataset$Result))
  
  # Calculate RMSE and MAE, ignoring NA values
  na_indices <- !is.na(testing_dataset$Result)  # Indices of non-NA values
  mse <- mean((testing_dataset$Result[na_indices] - predictions$pred[na_indices])^2)
  rmse <- sqrt(mse)
  mae <- mean(abs(testing_dataset$Result[na_indices] - predictions$pred[na_indices]))
  
  # Calculate average time for the race
  average_time <- mean(testing_dataset$Result, na.rm = TRUE)  # Assuming the time is in a column named 'Time'
  
  # Calculate normalized RMSE
  normalized_ar_mae <- mae / average_time
  normalized_ar_rmse <- rmse / average_time
  
  # Store the results
  result_df[nrow(result_df) + 1, ] <- c(race_name, rmse, mae, NA, normalized_ar_mae, normalized_ar_rmse, ifelse(grepl("gold", dataset_name), "G", "B"))
  
  # Predict results for the year 2024
  predictions_2024 <- predict(ar_model, n.ahead = 1)
  
  # Store the 2024 predictions
  result_df[nrow(result_df), "AR_2024_Predictions"] <- tail(predictions_2024$pred, 1)
}

# Save the results to a CSV file
write.csv(result_df, "ar_results.csv", row.names = FALSE)
```

```{r}
ar_results <- read.csv("~/Desktop/ds340w/ar_results.csv")
head(ar_results, n = Inf)
```

```{r}
RMSE2 <- knn_results %>%
  left_join(ar_results, by = c("Race", "Medal")) %>%
  select("Race", "Medal", "Normalized_KNN_RMSE", "Normalized_AR_RMSE", "Normalized_KNN_MAE", "Normalized_AR_MAE") %>%
  mutate(Smallest_RMSE = ifelse(Normalized_KNN_RMSE < Normalized_AR_RMSE, "KNN", "AR")) %>%
  mutate(Smallest_MAE = ifelse(Normalized_KNN_MAE < Normalized_AR_MAE, "KNN", "AR"))

head(RMSE2, n = Inf)
```

```{r}
# Calculate average normalized RMSE
avg_knn_norm_rmse <- mean(knn_results$Normalized_KNN_RMSE, na.rm = TRUE)

# Calculate average normalized MAE
avg_knn_norm_mae <- mean(knn_results$Normalized_KNN_MAE, na.rm = TRUE)

avg_knn_norm_rmse
avg_knn_norm_mae
```

```{r}
# Calculate smallest normalized RMSE
min_knn_norm_rmse <- min(knn_results$Normalized_KNN_RMSE, na.rm = TRUE)

# Calculate largest normalized RMSE
max_knn_norm_rmse <- max(knn_results$Normalized_KNN_RMSE, na.rm = TRUE)

# Calculate smallest normalized MAE
min_knn_norm_mae <- min(knn_results$Normalized_KNN_MAE, na.rm = TRUE)

# Calculate largest normalized MAE
max_knn_norm_mae <- max(knn_results$Normalized_KNN_MAE, na.rm = TRUE)

min_knn_norm_rmse
max_knn_norm_rmse
min_knn_norm_mae
max_knn_norm_mae
```

```{r}
#plot and include 2024 predictions
for (event in selected_events) {
  event_data <- subset(olympics_with_knn_predictions, Event == event)
  plot <- plot_gold_vs_bronze(event_data, event)
  print(plot)
}
```

```{r}
RMSE <- lm_results %>%
  left_join(knn_results, by = c("Race", "Medal")) %>%
  select("Race", "Medal", "Normalized_LM_RMSE", "Normalized_KNN_RMSE", "Normalized_LM_MAE", "Normalized_KNN_MAE") %>%
  mutate(Smallest_RMSE = ifelse(Normalized_LM_RMSE < Normalized_KNN_RMSE, "LM", "KNN")) %>%
  mutate(Smallest_MAE = ifelse(Normalized_LM_MAE < Normalized_KNN_MAE, "LM", "KNN"))

head(RMSE, n = Inf)
```

```{r}
comparison <- merge(lm_results, knn_results, by = c("Race", "Medal"))

final_comp <- merge(comparison, ar_results, by = c("Race", "Medal"))

final_comp <- final_comp %>%
  select("Medal", "Race", "Normalized_LM_RMSE", "Normalized_KNN_RMSE", "Normalized_AR_RMSE", "Normalized_LM_MAE", "Normalized_KNN_MAE", "Normalized_AR_MAE") %>%
  mutate(lowest_MAE = ifelse(pmin(Normalized_LM_MAE, Normalized_KNN_MAE, Normalized_AR_MAE) == Normalized_LM_MAE, "LM", ifelse(Normalized_KNN_MAE < Normalized_AR_MAE, "KNN", "AR"))) %>%
  mutate(lowest_RMSE = ifelse(pmin(Normalized_LM_RMSE, Normalized_KNN_RMSE, Normalized_AR_RMSE) == Normalized_LM_RMSE, "LM", ifelse(Normalized_KNN_RMSE < Normalized_AR_RMSE, "KNN", "AR")))

```




